### ISSUE TITLE
Mob spawners not spawning mobs

### ISSUE THREAD

**Issue by mtbrenner** [Electrofried/Pixelmon-Galaxies#10]
I verified that these these mob spawners don't spawn mobs:
cave spider (found in world)
slime (spawner converted with crafted slime spawn egg)
witch (spawner converted with crafted witch spawn egg)

Verified working:
skeleton, creeper, zombie, enderman, ancient golem (embers)

**Comment by Electrofried** [comment]
This is an issue with the pixelmon mod and the way they stop spawning of hostiles. Nothing I can do about it, please report to the pixelmon devs if you would like them to fix it however they have said multiple times they do not consider it an issue due to pixelmon providing mob drops.
