### ISSUE TITLE
No way to create RF power in the pack to power the electric arc furnace

### ISSUE THREAD

**Issue by Solverbolt** [Electrofried/Pixelmon-Galaxies#13]
Version is current as of Yesterday when we installed the server. 

I have attempted every option available. from rf transformer to every type of connector.  There is no way to create rf or convert joules to rf in this pack, which means its impossible to create steel, in order to make something like the Coal Coke Oven, which requires a machine that can craft the blocks, or turbines.  All the turbines for every RF option are locked behind steel as the needed material

**Comment by Electrofried** [comment]
Re-read the quests :)
There is one that tells you to make the block from magneticraft that converts Magneticraft energy to RF.

**Comment by Solverbolt** [comment]
wow. Okay, so apparently you do not read things all that well. Good to know. I will let the admins of a few servers know to drop this pack from their list.  As I have read the other closed issues, and its obvious that you consider yourself some savant, but really you just a poor excuse of a the most popular kid with down-syndrome.
