### ISSUE TITLE
Storage no mor-age!

### ISSUE THREAD

**Issue by TheSilverRose13** [Electrofried/Pixelmon-Galaxies#4]
Seems when you break a block with any sort of inventory, say a chest or a furnace, etc, you loose anything inside it. Happened on a sieve-the beginning ones-furnace, and chests as well.

**Comment by Electrofried** [comment]
This seems to only effect if you attempt to use ultimine to break the block. Breaking them normally will break the block without issue and the drops will be returned. For now just make sure not to use ultimine to break blocks. This is an issue with an interaction with spongeforge and FTB Ultimine. 
I will see if it can be resolved or replace Ultimine with another option in an upcoming patch.
Thanks!

**Comment by Electrofried** [comment]
fixed in latest release.
