### ISSUE TITLE
Landing on Hellus impossible (SP)

### ISSUE THREAD

**Issue by mtbrenner** [Electrofried/Pixelmon-Galaxies#5]
On Single Player I built a space station, warped to Hellus and tried to land with a rocket. First, I got booted off the rocket when entering the Nether dimension. Then the Nether has a bedrock ceiling making it inaccessible. I also tried launching a rocket from the bedrock ceiling to the space station. This also failed. My guess is that because it is the actual Nether dimension with dimid -1 the coordinates are transformed 1:8 and Advanced Rocketry doesn't handle that well.  Maybe the planet should just be a normal planet with hell biome.

**Comment by Electrofried** [comment]
Fixed in latest release.
