### ISSUE TITLE
Endus Rocket Disappears, egg and portals do not spawn after killing the dragon

### ISSUE THREAD

**Issue by layo12345** [Electrofried/Pixelmon-Galaxies#6]
Hiya, basically the rocket disappears when landing on Endus, probably due to it landing in the void, and when defeating the dragon, neither the portals or the dragon egg spawns, this makes it impossible to get chorus fruit and dragon heads and all that, thank you in advance

**Comment by Electrofried** [comment]
There are flying pokemon as well as jetpacks and magical flight that will allow you to fly to the outer islands and obtain chorus fruit, not much can be done about rockets not landing on islands as this is an advanced  rocketry issue failing to find a suitable landing location. 
I recommend launching rockets from 0, 0 to avoid issues with landing.
